<a href="https://colab.research.google.com/github/Nataliahfk/Pandas_transformacion_y_manipulacion_datos/blob/main/Ejercicio_Normalizacion_JSON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Proyecto Desafío 1: Ventas Online**

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopiló un conjunto de datos que contiene los clientes que más gastaron en productos durante los 5 días de ventas, que es la duración del evento. Este análisis identificará al cliente con la mayor compra esta semana, quien recibirá un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer más clientes.

La base de datos utilizada en este análisis es dados_vendas_clientes.json y contiene información importante sobre los clientes, como el nombre registrado del cliente, el monto total pagado al momento de la compra y el día de la compra.

Sabiendo esta información, el desafío del proyecto 1: ventas online será abrir la base de datos con Pandas y aplicar json_normalize.

In [46]:
# Importar Pandas
import pandas as pd

In [47]:
# Leer el archivo json con read_json
ventas = pd.read_json('/content/dados_vendas_clientes.json')
ventas.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [48]:
# Aplicar json_normalize en la columna dados_vendas
ventas = pd.json_normalize(ventas['dados_vendas'])
# Mostrar valores
ventas

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

**Proyecto Desafío 2:**

Administración de Condominios
Administrar condominios es una tarea que requiere mucha atención y organización. Entre las diversas responsabilidades de gestión se encuentra el cobro del alquiler a los inquilinos. Para garantizar la buena salud financiera de la empresa, es fundamental que estos pagos se realicen de forma regular y puntual. Sin embargo, sabemos que esto no siempre sucede.

Teniendo esto en cuenta, propongo un desafío de procesamiento de datos con el objetivo de analizar el retraso en el pago del alquiler en el condominio de algunos residentes. Pongo a disposición la base de datos dados_locacao_imoveis.json, que contiene información sobre el departamento de los inquilinos, el día acordado para el pago del alquiler, el día en que se realiza el pago del alquiler y el monto del alquiler.

In [49]:
import pandas as pd

In [50]:
alquiler = pd.read_json('/content/dados_locacao_imoveis.json')
alquiler.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [51]:
alquiler = pd.json_normalize(alquiler['dados_locacao'])
alquiler

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

**Etapa 2**

**Proyecto Desafío 1: Ventas Online**

Leímos la base de datos en el desafío anterior, ahora podemos seguir adelante con la transformación de estos datos. Así, el nuevo desafío del proyecto 1 será dividido en algunas metas:

- Eliminar datos en listas dentro del DataFrame;
- Verificar tipos de datos;
- Identificar columnas numéricas;
- Transformar la columna numérica a tipo numérico.

In [52]:
# Colectar los valores de las columnas y verificar
columnas = list(ventas.columns)
columnas

['Data de venda', 'Cliente', 'Valor da compra']

In [53]:
# Dividir los datos de las listas
ventas = ventas.explode(columnas[1:])
ventas

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [54]:
# Resetear los index de las líneas
ventas.reset_index(inplace=True, drop=True)
ventas

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [55]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [56]:
# La columna numérica es el 'Valor da compra'
ventas['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

In [57]:
# Iniciar la transformación
# Import de la biblioteca numpy
import numpy as np

In [58]:
# Remover los textos presentes en la base
# Cambiar las comas separadoras del decimal por punto
ventas['Valor da compra'] = ventas['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',','.').strip())
# Cambiar los tipo de datos para float
ventas['Valor da compra'] = ventas['Valor da compra'].astype(np.float64)
# Verificar la transformación
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [59]:
ventas['Valor da compra']

0     836.50
1     573.33
2     392.80
3     512.34
4     825.31
5     168.07
6     339.18
7     314.69
8     682.05
9     386.34
10    622.65
11    630.79
12    390.30
13    759.16
14    334.47
15    678.78
16    314.24
17    311.15
18    899.16
19    885.24
Name: Valor da compra, dtype: float64

**Projecto Desafio 2: Administración de Condominios**

In [60]:
columna_alquiler = list(alquiler.columns)
columna_alquiler

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [61]:
alquiler = alquiler.explode(columna_alquiler[1:])
alquiler

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [62]:
alquiler.reset_index(inplace=True, drop=True)
alquiler

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [63]:
alquiler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [64]:
# Cambiar datos
import numpy as np

In [65]:
alquiler['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [66]:
alquiler['valor_aluguel'] = alquiler['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(',','.').replace('reais','').strip())
alquiler['valor_aluguel'] = alquiler['valor_aluguel'].astype(np.float64)
alquiler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [67]:
alquiler['valor_aluguel']

0     1000.0
1     2500.0
2     1100.0
3     2600.0
4     1200.0
5     2700.0
6     1300.0
7     2800.0
8     1400.0
9     2900.0
10    1500.0
11    1200.0
12    1600.0
13    1300.0
14    1700.0
15    1400.0
16    1800.0
17    1500.0
18    1900.0
19    1600.0
20    2000.0
21    1000.0
22    2100.0
23    1100.0
24    2200.0
25    1200.0
26    2300.0
27    2100.0
28    2400.0
29    2200.0
Name: valor_aluguel, dtype: float64